### ISSUE TITLE
Removed griddly events parameter?

### ISSUE THREAD

**Issue by ithielnor** [programcsharp/griddly#33]
Chris,

Why did you remove the parameter for all the griddly specific events?

https://github.com/ithielnor/griddly/commit/26aeca197fe6551c406c84c2dfdf1ace1038e2b6

This is used by M3 to get a reference to the source grid. Do you have a better way to do it?

**Comment by programcsharp** [comment]
Oh, I didn't realize we were using those. I did a standardization because
we had about 3 different calling conventions for events. Some were using
multiple params, some with a data object, some just passing the griddly.

If you want to pass the griddly again just to make things doubly clear,
that's fine, but we need to standardize the event pattern. Maybe pass {
griddly: this.$element, ... } for all events if you want to do it that way.

Why can't you use $(this) or $(e.target) to get the griddly, depending on
context?

**Comment by ithielnor** [comment]
I'm delegating the handler to document. What is the target of a custom
event?

**Comment by programcsharp** [comment]
And also, trigger only passes the first arg. It can be an array of params
to use, but this (the way it was before the fix, and what precipitated my
change):

                this.$element.trigger("refresh.griddly", $element,
                {
                    start: startRecord,
                    pageSize: currentPageSize,
                    count: count
                });

won't work at all -- the data is never accessible because the param is
never passed.

**Comment by programcsharp** [comment]
Why wouldn't it be the element you trigger it off of? Looks like it is:
http://jsfiddle.net/nhmasc5u/1/

Chris

**Comment by ithielnor** [comment]
I'll test that out. If it is, then that's the right way to do it.
